import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { formatCurrency, formatDate, formatTime } from "@/utils/format";
import { APP_NAME } from "@/constants";

interface TicketData {
  bookingNumber: string;
  movieTitle: string;
  theatre: string;
  screen?: string;
  date: string | Date;
  time: string | Date;
  seats: string;
  amount: number;
  customerName: string;
  qrCodeDataUrl?: string;
}

function showTimeLabel(time: string | Date): string {
  if (typeof time === "string") {
    // Already formatted ("7:00 PM") or ISO — try Date parse for ISO only
    const parsed = Date.parse(time);
    if (!Number.isNaN(parsed) && /\d{4}-\d{2}-\d{2}|T/.test(time)) {
      return formatTime(new Date(parsed));
    }
    return time;
  }
  return formatTime(time);
}

/** Helvetica/WinAnsi cannot encode ₹ and many Unicode glyphs. */
function pdfSafe(text: string): string {
  return String(text ?? "")
    .replace(/\u20B9/g, "Rs.")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "?");
}

/**
 * Generate an e-ticket PDF (pdf-lib — no filesystem font deps, works under Turbopack).
 */
export async function generateTicketPDF(data: TicketData): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]); // A4
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const crimson = rgb(0.88, 0.11, 0.28);
  const ink = rgb(0.07, 0.07, 0.07);
  const muted = rgb(0.4, 0.4, 0.4);
  const gold = rgb(0.98, 0.75, 0.14);
  const softRed = rgb(0.996, 0.95, 0.95);

  // Header bar
  page.drawRectangle({
    x: 0,
    y: 761.89,
    width: 595.28,
    height: 80,
    color: rgb(0.04, 0.05, 0.06),
  });
  page.drawText(pdfSafe(APP_NAME), {
    x: 50,
    y: 795,
    size: 26,
    font: fontBold,
    color: crimson,
  });
  page.drawText("E-TICKET", {
    x: 450,
    y: 800,
    size: 12,
    font: fontBold,
    color: gold,
  });

  page.drawText("Booking Confirmed", {
    x: 50,
    y: 720,
    size: 20,
    font: fontBold,
    color: ink,
  });
  page.drawText(pdfSafe(`Booking ID: ${data.bookingNumber}`), {
    x: 50,
    y: 698,
    size: 10,
    font,
    color: muted,
  });

  page.drawLine({
    start: { x: 50, y: 680 },
    end: { x: 545, y: 680 },
    thickness: 1,
    color: rgb(0.9, 0.9, 0.9),
  });

  const rows: [string, string][] = [
    ["Movie", data.movieTitle],
    ["Theatre", data.theatre],
    ["Screen", data.screen || "Audi 1"],
    ["Date", formatDate(data.date)],
    ["Show Time", showTimeLabel(data.time)],
    ["Seats", data.seats],
    ["Guest", data.customerName],
    ["Amount Paid", pdfSafe(formatCurrency(data.amount))],
  ];

  let y = 650;
  for (const [label, value] of rows) {
    page.drawText(label, { x: 50, y, size: 10, font, color: muted });
    const text = pdfSafe(String(value || "-")).slice(0, 48);
    page.drawText(text, { x: 180, y, size: 12, font: fontBold, color: ink });
    y -= 28;
  }

  if (data.qrCodeDataUrl?.startsWith("data:image")) {
    try {
      const base64 = data.qrCodeDataUrl.split(",")[1];
      const bytes = Buffer.from(base64, "base64");
      const png = await doc.embedPng(bytes);
      const size = 140;
      page.drawImage(png, {
        x: 400,
        y: 500,
        width: size,
        height: size,
      });
      page.drawText("Scan at entrance", {
        x: 420,
        y: 482,
        size: 9,
        font,
        color: muted,
      });
    } catch {
      /* skip QR if embed fails */
    }
  }

  const bannerY = Math.min(y, 430) - 40;
  page.drawRectangle({
    x: 50,
    y: bannerY - 20,
    width: 495,
    height: 50,
    color: softRed,
  });
  page.drawText("Present this ticket (or QR code) at the theatre entrance.", {
    x: 70,
    y: bannerY,
    size: 11,
    font,
    color: crimson,
  });

  page.drawText(
    pdfSafe(`Generated by ${APP_NAME} - ${new Date().toISOString()}`),
    {
      x: 50,
      y: 40,
      size: 8,
      font,
      color: muted,
    }
  );

  const bytes = await doc.save();
  return Buffer.from(bytes);
}
