import PDFDocument from "pdfkit";
import { formatCurrency, formatDate, formatTime } from "@/utils/format";
import { APP_NAME } from "@/constants";

interface TicketData {
  bookingNumber: string;
  movieTitle: string;
  theatre: string;
  screen?: string;
  date: string | Date;
  time: string | Date;
  seats: string;
  amount: number;
  customerName: string;
  qrCodeDataUrl?: string;
}

export async function generateTicketPDF(data: TicketData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.rect(0, 0, doc.page.width, 80).fill("#0B0D10");
    doc.fillColor("#E11D48").fontSize(28).text(APP_NAME, 50, 28);
    doc.fillColor("#FBBF24").fontSize(12).text("E-TICKET", 450, 35);

    doc.fillColor("#111").fontSize(22).text("Booking Confirmed", 50, 110);
    doc.fontSize(10).fillColor("#666").text(`Booking ID: ${data.bookingNumber}`, 50, 140);

    doc.moveTo(50, 165).lineTo(545, 165).strokeColor("#E5E5E5").stroke();

    const rows = [
      ["Movie", data.movieTitle],
      ["Theatre", data.theatre],
      ["Screen", data.screen || "Audi 1"],
      ["Date", formatDate(data.date)],
      ["Show Time", typeof data.time === "string" ? data.time : formatTime(data.time)],
      ["Seats", data.seats],
      ["Guest", data.customerName],
      ["Amount Paid", formatCurrency(data.amount)],
    ];

    let y = 190;
    for (const [label, value] of rows) {
      doc.fillColor("#888").fontSize(10).text(label, 50, y);
      doc.fillColor("#111").fontSize(12).text(String(value), 200, y, { width: 300 });
      y += 28;
    }

    if (data.qrCodeDataUrl?.startsWith("data:image")) {
      try {
        const base64 = data.qrCodeDataUrl.split(",")[1];
        const img = Buffer.from(base64, "base64");
        doc.image(img, 400, 190, { width: 140, height: 140 });
        doc.fillColor("#666").fontSize(9).text("Scan at entrance", 420, 340);
      } catch {
        /* skip QR embed if buffer invalid */
      }
    }

    doc.rect(50, Math.max(y, 360) + 20, 495, 60).fill("#FEF2F2");
    doc
      .fillColor("#E11D48")
      .fontSize(11)
      .text(
        "Present this ticket (or QR code) at the theatre entrance.",
        70,
        Math.max(y, 360) + 40
      );

    doc
      .fillColor("#999")
      .fontSize(8)
      .text(`Generated by ${APP_NAME} · ${new Date().toISOString()}`, 50, 750);

    doc.end();
  });
}
